var slimeAIs = [
    {name:"Pathetic White Slime",
     color:'#fff',
     backImageName:'sky',
     legacySkyColor:'#00f',
     legacyGroundColor:'#888',
     legacyBallColor:'#ff0',
     newGroundColor:'#ca6',
     backTextColor:'#000',
     //initAI:setMasterSlime},
     initAI:setPatheticWhiteSlime},
    {name:"Angry Red Slime",
     color:'#f00',
     backImageName:'cave',
     legacySkyColor:'#1e5000',
     legacyGroundColor:'#444',
     legacyBallColor:'#88f',
     newGroundColor:'#444',
     backTextColor:'#fff',
     initAI:setAngryRedSlime},
    {name:"Slime Master",
     color:'#000',
     backImageName:'sunset',
     legacySkyColor:'#623939',
     legacyGroundColor:'#00a800',
     legacyBallColor:'#fff',
     newGroundColor:'#655040',
     backTextColor:'#fff',
     initAI:setMasterSlime}
];
